AWSTemplateFormatVersion: "2010-09-09"
Description: "ECS Cluster and Task Definition for Python Logging"
Parameters:
  ECSClusterName:
    Type: String
    Default: "logging-cluster"
    Description: Name of ECS Cluster
  ContainerImageTag:
    Type: String
    Default: "python-logging:latest"
    Description: Container image tag(Pulls from your private ECR Repository)
  ContainerName:
    Type: String
    Default: "python"
    Description: Name of ECS Container
  TaskDefFamilyName:
    Type: String
    Default: "python-logging-task-def"
    Description: Name of Task Definition
  TaskExecutionRoleName:
    Type: String
    Default: "ecsTaskExecutionRole"
    Description: Name of ECS Task Role

Resources:
  ECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: !Ref ECSClusterName
      ClusterSettings:
        - Name: "containerInsights"
          Value: "disabled"
      CapacityProviders:
        - "FARGATE_SPOT"
        - "FARGATE"

  ECSTaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      ContainerDefinitions:
        - Essential: true
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ContainerImageTag}"
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              awslogs-group: !Sub "/ecs/${TaskDefFamilyName}"
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: "ecs"
          Name: !Ref ContainerName
      Family: !Ref TaskDefFamilyName
      TaskRoleArn: !GetAtt IAMRole.Arn
      ExecutionRoleArn: !GetAtt IAMRole.Arn
      NetworkMode: "awsvpc"
      RequiresCompatibilities:
        - "FARGATE"
      Cpu: "256"
      Memory: "512"

  IAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      RoleName: !Ref TaskExecutionRoleName
      AssumeRolePolicyDocument: '{"Version":"2008-10-17","Statement":[{"Sid":"","Effect":"Allow","Principal":{"Service":"ecs-tasks.amazonaws.com"},"Action":"sts:AssumeRole"}]}'
      MaxSessionDuration: 3600
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess"
        - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
